### ISSUE TITLE
Request for "BuffBlock"

### ISSUE THREAD

**Issue by Doudeh** [PlaskED/BuffBlock#5]
Very good job and thanks for everything.
is it possible to add some feature (new buff block):
_Detect Greater invisibility
Unending Breath
Lay on Hands
Shadow Protection
Fire Shield
Dampen magic
Amplify magic_

**Comment by PlaskED** [comment]
Busy months! I can add them in next update

**Comment by PlaskED** [comment]
Detect Greater invisibility
Unending Breath
Lay on Hands
Shadow Protection (Only prayer)
Fire Shield
Dampen magic
Amplify magic

These changes are added into the coming release, probably today. Regular Shadow Protection was not included since it shares name with the buff given from greater shadow protection potion.
